### ISSUE TITLE
Update link to git repo in wiki

### ISSUE THREAD

**Issue by mksmtn** [pantuza/c-project-template#2]
In _Get Started_ article there is a command

    git clone git@github.com:pantuza/c-project-template.git

which gives an error (git version 2.17.1)

    The authenticity of host 'github.com (140.82.118.4)' can't be established.

If you change it to

    git clone https://github.com/pantuza/c-project-template.git

there will be no errors

**Comment by pantuza** [comment]
Hey @mksmtn , thank you for taking some time to report that! I really appreciate it. 
I've updated [C Project Template Wiki](https://github.com/pantuza/c-project-template/wiki/Get-started) to not rely on SSH to clone the project but on HTTPS instead.
